search:
    iteration_limit: 1000
    time_limit: 120
    max_transforms: 6
expansion:
  uspto:
    - ./data/uspto_model.onnx
    - ./data/uspto_templates.csv
  ringbreaker:
    - ./data/uspto_ringbreaker_model.onnx
    - ./data/uspto_ringbreaker_templates.csv.gz
filter:
  uspto: ./data/uspto_filter_model.onnx
stock:
  askcos: ./data/buy_db_askcos.hdf5
#  zinc:./data/zinc_stock.hdf5
